# Generated by Django 5.2.1 on 2025-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camara',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='camara',
            name='url_stream',
        ),
        migrations.AddField(
            model_name='camara',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camara',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
