# Generated by Django 5.2.7 on 2025-10-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0002_add_activa_field'),
        ('camaras', '0002_remove_camara_nombre_remove_camara_url_stream_and_more'),
    ]

    operations = [
    ]
