# Generated by Django 5.2.7 on 2025-10-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0003_merge_20251011_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camara',
            options={'verbose_name': 'Cámara', 'verbose_name_plural': 'Cámaras'},
        ),
    ]
