# Generated by Django 5.2.7 on 2025-10-13 00:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0004_alter_camara_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='fecha_instalacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
