# Generated by Django 5.2.7 on 2025-10-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0005_alter_camara_fecha_instalacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='indice_webcam',
            field=models.IntegerField(default=0, help_text='Índice de la webcam local (0, 1, 2, etc.)'),
        ),
        migrations.AddField(
            model_name='camara',
            name='ruta_video',
            field=models.CharField(blank=True, help_text='Ruta del archivo de video para pruebas', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='camara',
            name='tipo_fuente',
            field=models.CharField(choices=[('WEBCAM', 'Webcam Local'), ('IP', 'Cámara IP'), ('VIDEO', 'Archivo de Video'), ('IRIUN', 'IriunWebcam')], default='WEBCAM', help_text='Tipo de fuente de video', max_length=20),
        ),
        migrations.AddField(
            model_name='camara',
            name='url_stream',
            field=models.CharField(blank=True, help_text='URL para cámara IP o IriunWebcam (ej: http://192.168.1.100:8080/video)', max_length=500, null=True),
        ),
    ]
