# Generated by Django 5.2.7 on 2025-10-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infracciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='infraccion',
            new_name='infraccione_fecha_h_c5443c_idx',
            old_name='infraccione_fecha_h_8e5c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='infraccion',
            new_name='infraccione_vehicul_2363dd_idx',
            old_name='infraccione_vehicul_9a7b2c_idx',
        ),
    ]
