# Generated by Django 5.2.7 on 2025-10-13 00:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infracciones', '0002_rename_infraccione_fecha_h_8e5c8a_idx_infraccione_fecha_h_c5443c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventodeteccion',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prediccionaccidente',
            name='fecha_prediccion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
