# Generated by Django 5.2.7 on 2025-10-31 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infracciones', '0003_alter_eventodeteccion_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_pronto_pago', models.DecimalField(decimal_places=2, default=0, help_text='Descuento porcentual por pago dentro de 5 días', max_digits=5)),
                ('aumento_reincidencia', models.DecimalField(decimal_places=2, default=0, help_text='Aumento porcentual por infracciones previas', max_digits=5)),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('GENERADA', 'Generada'), ('NOTIFICADA', 'Notificada'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='GENERADA', max_length=20)),
                ('numero_multa', models.CharField(max_length=20, unique=True)),
                ('infraccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='infracciones.infraccion')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='infracciones.vehiculo')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
