"""
Django settings for sistema_infraccion project.

Generated by 'django-admin startproject' using Django 5.0.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gn5&j25cio^+vtm*xvq$-antkmsniq#pu4$uw*u!wa6b7_1+pr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CSRF_TRUSTED_ORIGINS = ['https://sistemainfracc.azurewebsites.net']

ALLOWED_HOSTS = ['sistemainfracc.azurewebsites.net', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ProyectoSQL',
    'camaras',
    'dashboard',
    'infracciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_infraccion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_infraccion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': os.getenv('DB_NAME', 'pruebita_infraccion'),
        'USER': os.getenv('DB_USER', 'adminsa@pruebaazure13'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'admin2004A$'),
        'HOST': os.getenv('DB_HOST', 'pruebaazure13.database.windows.net'),
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Sistema de Infracciones IA",
    "site_header": "Sistema de Infracciones con IA",
    "site_brand": "Infracciones IA",
    "welcome_sign": "Bienvenido al Sistema de Detección de Infracciones con Inteligencia Artificial",
    "copyright": "Sistema de Infracciones IA © 2025",

    # Logo opcional
    "site_logo": None,

    # 🎨 Temas Bootswatch
    "theme": "minty",
    "dark_mode_theme": "darkly",

    "icons": {
        "auth": "fas fa-users",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users-cog",
        "camaras.Camara": "fas fa-video",
        "infracciones.TipoInfraccion": "fas fa-exclamation-triangle",
        "infracciones.Vehiculo": "fas fa-car",
        "infracciones.Infraccion": "fas fa-file-invoice",
        "infracciones.PerfilConductor": "fas fa-user-shield",
        "infracciones.PrediccionAccidente": "fas fa-chart-line",
        "infracciones.EventoDeteccion": "fas fa-bell",
        "ml_predicciones.ModeloEntrenamiento": "fas fa-brain",
        "ml_predicciones.DatasetEntrenamiento": "fas fa-database",
    },

    "order_with_respect_to": ["camaras", "infracciones", "ml_predicciones", "auth"],
    
    "custom_links": {
        "infracciones": [{
            "name": "Dashboard de Infracciones", 
            "url": "admin:index",
            "icon": "fas fa-chart-pie",
        }]
    },
}


JAZZMIN_UI_TWEAKS = {
    "theme": "minty",
    "dark_mode_theme": "darkly",
}
