"""
Django settings for seguridad project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Si usas modelos preentrenados, configura el cache
os.environ['YOLO_CACHE_DIR'] = os.path.join(os.path.dirname(__file__), '.yolo_cache')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_v*bl)+w#6dfj%2_cl8+k$-_d3!f((14$sr!&b8tf2p5y1ca5v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else [
    'seguridadtesis-a6gtbhb2eqbdasgv.eastus2-01.azurewebsites.net',
    '.azurewebsites.net',
    'localhost',
    '127.0.0.1'
]

CSRF_TRUSTED_ORIGINS = [
    'https://seguridadtesis-a6gtbhb2eqbdasgv.eastus2-01.azurewebsites.net',
    'https://seguridadtesis.azurewebsites.net',
]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'camaras',
    'dashboard',
    'infracciones',
    'ml_predicciones',
    'vision_ai',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- Agregado

]

ROOT_URLCONF = 'seguridad.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'seguridad.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'django_infraccionsqlserver',
        'USER': 'sa',
        'PASSWORD': '1234',
        'HOST': 'BACILIO\\SQLEXPRESS',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}

# Configuración de cámara EZVIZ
EZVIZ_CONFIG = {
    'ip': '192.168.1.32',
    'usuario': 'admin',
    'password': 'NXLTPJ',  # 🔒 Verification Code
    'puerto_rtsp': 554,
    'url_rtsp': 'rtsp://admin:NXLTPJ@192.168.1.32:554/h264_stream',
    'resolucion': '2304x1296',
    'activa': True,
}

# Configuración de cámaras disponibles
CAMARAS_DISPONIBLES = [
    {
        'id': 'ezviz_h6c',
        'nombre': 'Cámara EZVIZ H6c Pro - Exterior',
        'url_rtsp': EZVIZ_CONFIG['url_rtsp'],
        'tipo': 'rtsp',
        'ubicacion': 'Entrada Principal',
        'activa': True
    },
    {
        'id': 'local_0',
        'nombre': 'Cámara Local 0',
        'url_rtsp': 0,
        'tipo': 'local',
        'ubicacion': 'Interna',
        'activa': False
    }
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
BASE_DIR = Path(__file__).resolve().parent.parent

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Sistema de Infracciones IA",
    "site_header": "Sistema de Infracciones con IA",
    "site_brand": "Infracciones IA",
    "welcome_sign": "Bienvenido al Sistema de Detección de Infracciones con Inteligencia Artificial",
    "copyright": "Sistema de Infracciones IA © 2025",

    # Logo opcional
    "site_logo": None,

    # 🎨 Temas Bootswatch
    "theme": "minty",
    "dark_mode_theme": "darkly",

    "icons": {
        "auth": "fas fa-users",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users-cog",
        "camaras.Camara": "fas fa-video",
        "infracciones.TipoInfraccion": "fas fa-exclamation-triangle",
        "infracciones.Vehiculo": "fas fa-car",
        "infracciones.Infraccion": "fas fa-file-invoice",
        "infracciones.PerfilConductor": "fas fa-user-shield",
        "infracciones.PrediccionAccidente": "fas fa-chart-line",
        "infracciones.EventoDeteccion": "fas fa-bell",
        "ml_predicciones.ModeloEntrenamiento": "fas fa-brain",
        "ml_predicciones.DatasetEntrenamiento": "fas fa-database",
    },

    "order_with_respect_to": ["camaras", "infracciones", "ml_predicciones", "auth"],
    
    "custom_links": {
        "infracciones": [{
            "name": "Dashboard de Infracciones", 
            "url": "admin:index",
            "icon": "fas fa-chart-pie",
        }]
    },
}


JAZZMIN_UI_TWEAKS = {
    "theme": "minty",
    "dark_mode_theme": "darkly",
}

SUNARP_BASE_URL = "https://consultavehicular-sunarp.com/buscar"
SUNARP_TIMEOUT = 10
SUNARP_RETRY_ATTEMPTS = 3

LOGIN_REDIRECT_URL = 'dashboard_home'
LOGIN_URL = 'login'
